### ISSUE TITLE
Do a tag

### ISSUE THREAD

**Issue by traversaro** [robotology/yarp-device-ovrheadset#3]
For including this repo in the superbuild releases process, it would be convenient if we just tagged an initial version, even a `v0.1.0` is probably ok.

**Comment by drdanz** [comment]
I'd like to wait to remove the device from YARP before tagging it here...

**Comment by traversaro** [comment]
As this was done in https://github.com/robotology/yarp/pull/2465 , could it make sense to do a tag in this repo?

**Comment by drdanz** [comment]
Sure, does anyone volunteer to take care of this?

**Comment by traversaro** [comment]
I can do that, no problem. I suggested anyhow to change the version to avoid confusion with the YARP version, what do you think?

**Comment by drdanz** [comment]
> I can do that, no problem. I suggested anyhow to change the version to avoid confusion with the YARP version, what do you think?

I agree. Choose whatever version number you prefer, even though since this was already released as "stable", so perhaps `v1.0.0` would be better than `v0.1.0`

**Comment by traversaro** [comment]
Done in https://github.com/robotology/yarp-device-ovrheadset/releases/tag/v1.0.0 .
